# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ipyfuncs',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/ipyfuncs',
                'lib_path': 'ipyfuncs'},
  'syms': {'ipyfuncs.core': {'ipyfuncs.core.foo': ('core.html#foo', 'ipyfuncs/core.py')}}}
