"""`InteractiveShell` services that kernel clients drive remotely: introspection, evaluation, completion, signature help, and display publishing

Docs: https://AnswerDotAI.github.io/ipyfuncs/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/00_core.ipynb #da4d26dd
import typing, warnings, traceback, tokenize, inspect
from ast import literal_eval
from io import StringIO
from collections.abc import Mapping
from types import ModuleType, FunctionType, MethodType, BuiltinFunctionType
from inspect import signature
from fastcore.utils import patch, dict2obj
from fastcore.aio import maybe_await
from fastcore.funccall import get_schema_nm
from jedi import Interpreter, Script as jscript
from IPython.core.interactiveshell import InteractiveShell
from IPython.core.completer import ProvisionalCompleterWarning
from IPython.core.display import DisplayObject


# %% ../nbs/00_core.ipynb #5806526e
warnings.filterwarnings('ignore', category=ProvisionalCompleterWarning)

# %% ../nbs/00_core.ipynb #778181b4
def _safe_repr(obj, max_len=200):
    "Safely get the repr() of an object, truncating if it exceeds max_len."
    try:
        s = str(obj)
        return s[:max_len] + ("…" if len(s)>max_len else "")
    except Exception as e: return f"<repr error: {str(e)}>"

# %% ../nbs/00_core.ipynb #dbe51e8d
def _safe_sig(v):
    try: return str(signature(v))
    except Exception: return '(...)'

@patch
def user_items(self:InteractiveShell, max_len=200, xtra_skip=()):
    "Get user-defined vars & funcs from namespace."
    ns,nsh = self.user_ns,self.user_ns_hidden
    ignore = {'nbmeta', 'receive_nbmeta'}
    ignore.add(xtra_skip)
    rm_types = (type, FunctionType, ModuleType, MethodType, BuiltinFunctionType,
        *(getattr(typing, o, ()) for o in ('_SpecialGenericAlias', '_GenericAlias', '_SpecialForm')))
    user_items = {k: v for k, v in ns.items() if not k in ignore and k not in nsh}
    user_vars = {k:_safe_repr(v, max_len=max_len)
        for k, v in user_items.items() if not k.startswith('_') and not isinstance(v, rm_types)}
    user_fns = {k:_safe_sig(v) for k, v in user_items.items()
        if isinstance(v, FunctionType) and v.__module__ == '__main__' and not k.startswith('__')}
    return user_vars,user_fns

# %% ../nbs/00_core.ipynb #990bb484
def _rank(c, s):
    "Rank a completion `c` for text `s` with namespace `ns`."
    parts = s.split('.')
    is_public = not c.text.startswith('_')
    if c.type=='param': r=1
    elif c.mod=='__main__': r=2 # local
    elif len(parts)>1 and parts[0]==c.mod: r=3 # module
    elif c.mod=='builtins': r=4
    else: r=5
    return r if is_public else r+0.1

# %% ../nbs/00_core.ipynb #279e4f99
@patch
def ranked_complete(self:InteractiveShell, code, line_no=None, col_no=None):
    ns = self.user_ns
    lines = code.splitlines(True)
    if line_no: offset = sum(len(lines[i]) for i in range(line_no-1)) + col_no -1
    else: offset = len(code)
    cs = self.Completer.completions(code, offset)
    def _c(a):
        res = dict2obj(text=a.text, type=str(a.type or ''), signature=str(getattr(a, 'signature', '') or ''), start=a.start, end=a.end)
        res['mod'] = getattr(ns.get(a.text, None), '__module__', None)
        res['rank'] = _rank(res, s=code)
        return res
    return [_c(c) for c in cs if not c.text.startswith('__') or '__' in code]

# %% ../nbs/00_core.ipynb #4da89de3
def _maybe_eval(o):
    try:
        literal_eval(repr(o))
        return o
    except: return str(o)

# %% ../nbs/00_core.ipynb #4725fa05
@patch
def get_vars(self:InteractiveShell, vs:list, literal=True):
    "Get variables from namespace."
    ns = self.user_ns
    return {v:_maybe_eval(ns[v]) if literal else str(ns[v]) for v in vs if v in ns}

# %% ../nbs/00_core.ipynb #4bd28596
@patch
async def eval_exprs(self:InteractiveShell, vs:list, literal=True):
    "Evaluate expressions in namespace."
    ns,res = self.user_ns,{}
    for v in vs:
        try:
            e = await maybe_await(eval(v, ns))
            res[v] = _maybe_eval(e) if literal else str(e)
        except Exception as e: res[v] = f'<error type="{type(e).__name__}" desc="{e}">\n{traceback.format_exc()}</error>'
    return res

# %% ../nbs/00_core.ipynb #87c14582
def _get_schema(ns: dict, t):
    "Check if tool `t` has errors."
    try: schema = get_schema_nm(t, ns, pname='parameters', evalable=True, skip_hidden=True, dot2dash=True)
    except (KeyError, AttributeError): return f"`{t}` not found. Did you run it?"
    except Exception as e: return f"`{t}`: {e}."
    return {'type':'function', 'function':schema}

@patch
def get_schemas(self:InteractiveShell, fs:list):
    "Get schemas from namespace."
    return {f:_get_schema(self.user_ns, f) for f in fs}

# %% ../nbs/00_core.ipynb #558d9b8f
def _signatures(ns, s, line, col):
    ctx = Interpreter(s, [ns]).get_signatures(line, col)
    if not ctx: ctx = jscript(s).get_signatures(line, col)
    return ctx

@patch
def _sig_jedi(self:InteractiveShell, code, line_no=None, col_no=None):
    ns = self.user_ns
    ctx = _signatures(ns, code, line=line_no, col=col_no)
    if ctx:
        def _s(s): return dict(label=s.description, typ=s.type, mod=s.module_name, doc=s.docstring(), idx=s.index,
            params=[dict(name=p.name, desc=p.description) for p in s.params])
        return [_s(opt) for opt in ctx]
    return []

# %% ../nbs/00_core.ipynb #08348fa7
def _param_idx(code, cursor_pos):
    toks = []
    def op(s): return s == tokenize.OP
    g = tokenize.generate_tokens(StringIO(code[:cursor_pos]).readline)
    while True:
        try: toks.append(next(g))
        except (tokenize.TokenError, StopIteration): break
    depth,idx = 0,0
    for t in reversed(toks):
        if op(t.type) and t.string in ')]}': depth += 1
        elif op(t.type) and t.string in '([{':
            if depth == 0: return idx
            depth -= 1
        elif op(t.type) and t.string == ',' and depth == 0: idx += 1
    return 0

# %% ../nbs/00_core.ipynb #836c9059
@patch
def _sig_dyn(self:InteractiveShell, code, line_no=None, col_no=None):
    from IPython.utils.tokenutil import token_at_cursor
    lines = code.splitlines()
    cursor_pos = sum(len(l)+1 for l in lines[:line_no-1])+col_no if line_no else len(code)
    name = token_at_cursor(code, cursor_pos)
    info = self._object_find(name)
    if not (info.found and callable(info.obj)): return []
    try: sig = inspect.signature(info.obj)
    except (ValueError, TypeError): return []
    ps = list(sig.parameters.values())
    idx = _param_idx(code, cursor_pos)
    vp = next((i for i, p in enumerate(ps) if p.kind is p.VAR_POSITIONAL), None)
    if vp is not None and idx > vp: idx = vp   # *args soaks the positional overflow
    return [dict(label=name, typ=type(info.obj).__name__, mod=getattr(info.obj,'__module__',''), idx=idx,
        doc=getattr(info.obj,'__doc__','') or '', params=[dict(name=p.name, desc=str(p)) for p in ps])]

# %% ../nbs/00_core.ipynb #893e1908
@patch
def sig_help(self:InteractiveShell, code, line_no=None, col_no=None):
    "Get signature help for code at cursor position using dynamic analysis or jedi as a backup."
    return self._sig_dyn(code, line_no, col_no=col_no) or self._sig_jedi(code, line_no, col_no=col_no)

# %% ../nbs/00_core.ipynb #f2721159
@patch
def publish(self:InteractiveShell, data='', subtype='plain', mimetype='text', meta=None, update=False, **kw):
    if isinstance(data, DisplayObject): data,_ = self.display_formatter.format(data)
    elif not isinstance(data, Mapping): data = {f'{mimetype}/{subtype}': data}
    self.display_pub.publish(data, metadata=meta, transient=kw, update=update)
